name: evil_realtime
on:
  push:
  schedule:
    - cron: "0,30 * * * *"
  workflow_dispatch:

jobs:
  devil:
    name: evil_realtime
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4        

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: "pip"
     
      - name: Download Previous Vulnerability List
        uses: dawidd6/action-download-artifact@v5
        continue-on-error: true
        with:
          branch: main
          workflow: evil-realtime.yaml
          path: ./  

      - name: twitter key decode
        env:
          JSON_DECODE: ${{ secrets.NOGAS }}
        run: |
          echo -n $JSON_DECODE | base64 --decode > ./setting.ini

      - name: pip install
        run: pip install -r requirements.txt

      - name: schedule_evil_tweet
        if: github.event_name != 'workflow_dispatch'
        run: |
          mv ./realtime_data.json/realtime_data.json ./tmp.json
          rm -rf ./realtime_data.json
          mv tmp.json realtime_data.json
          python realtime_true.py nogaslighting

      - name: workflow_dispatch_evil_tweet
        if: github.event_name == 'workflow_dispatch'
        id: workflow_dispatch_evil_tweet
        run: |
          mv ./realtime_data.json/realtime_data.json ./tmp.json
          rm -rf ./realtime_data.json
          mv tmp.json realtime_data.json
          mkdir img
          python realtime_true.py nogaslighting

      - uses: actions/upload-artifact@v4
        with:
          name: realtime_data.json
          path: realtime_data.json
          if-no-files-found: error
          retention-days: 90          
