name: Artifacts Example
on:
  push:

jobs:
  upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Create Artifact
        run: echo "Hello World" > test.txt
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: test.txt
  download-artifact:
    runs-on: ubuntu-latest
    needs: upload-artifact
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: my-artifact
      - name: Read Artifact
        run: |
          echo "$ ls"
          ls
          echo "$ cat test.txt"
          cat test.txt